module.exports = {
    purge: [
        "./src/**/*.js",
        "./src/**/*.jsx",
        "./src/**/*.ts",
        "./src/**/*.tsx",
    ],
    theme: {
        extend: {
            colors: {
                transparent: "transparent",
                black: "#000",
                "black-lighter": "#272822",
                "grey-darker": "#606f7b",
                "grey-light": "#dae1e7",
                "grey-lighter": "#f1f5f8",
                white: "#ffffff",
                pink: "#db00a7",
                red: "#D95A44",
            },
            screens: {
                sm: "576px",
                md: "768px",
                lg: "992px",
                xl: "1200px",
            },
            fonts: {
                sans: [
                    "system-ui",
                    "BlinkMacSystemFont",
                    "-apple-system",
                    "Segoe UI",
                    "Roboto",
                    "Oxygen",
                    "Ubuntu",
                    "Cantarell",
                    "Fira Sans",
                    "Droid Sans",
                    "Helvetica Neue",
                    "sans-serif",
                ],
                serif: [
                    "Constantia",
                    "Lucida Bright",
                    "Lucidabright",
                    "Lucida Serif",
                    "Lucida",
                    "DejaVu Serif",
                    "Bitstream Vera Serif",
                    "Liberation Serif",
                    "Georgia",
                    "serif",
                ],
                mono: [
                    "Menlo",
                    "Monaco",
                    "Consolas",
                    "Liberation Mono",
                    "Courier New",
                    "monospace",
                ],
            },
        },
    },
    variants: {},
    plugins: [],
};
