backend:
  name: git-gateway
  branch: staging

media_folder: src/images
public_folder: /public

collections:
  - name: 'blog'
    label: 'Blog'
    slug: 'blog/{{slug}}'
    folder: 'src/posts'
    create: true
    media_folder: 'uploads'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Path', name: 'path', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'work'
    label: 'Work'
    slug: 'work/{{slug}}'
    folder: 'src/work'
    create: true
    media_folder: 'uploads'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Path', name: 'path', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Type', name: 'type', widget: 'hidden', default: 'work' }
      - { label: 'Body', name: 'body', widget: 'markdown' }